---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs
resources:
  - ./openebs/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/alerts
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: openebs
    target:
      kind: Namespace
