---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  node-shell:
    desc: Open a shell to a node [NODE=required]
    interactive: true
    cmd: kubectl node-shell -n kube-system -x {{.NODE}}
    requires:
      vars: [NODE]
    preconditions:
      - kubectl get nodes {{.NODE}}
      - kubectl node-shell --version
      - which kubectl

  cleanup-pods:
    desc: Clean up pods with a Failed/Pending/Succeeded phase [K8S_CLUSTER=main]
    preconditions:
      - which kubectl
    cmds:
      - for: [Failed, Pending, Succeeded]
        cmd: kubectl delete pods --all-namespaces --field-selector status.phase={{.ITEM}} --ignore-not-found=true

  sync-externalsecrets:
    desc: Force sync all ExternalSecret resources
    preconditions:
      - which kubectl
    vars:
      SECRETS:
        sh: kubectl get externalsecret --all-namespaces --no-headers --output=jsonpath='{range .items[*]}{.metadata.namespace},{.metadata.name}{"\n"}{end}'
    cmds:
      - for:
          var: SECRETS
          split: "\n"
        cmd: kubectl --namespace {{splitList "," .ITEM | first}} annotate externalsecret {{splitList "," .ITEM | last}} force-sync="{{now | unixEpoch}}" --overwrite
