---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: tivoli
      auth:
        serviceAccountSecretRef:
          name: onepassword-secret
          key: token
          namespace: external-secrets
      integrationInfo: # this is optional and defaulted
        name: integration-info
        version: v1
