# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:rj+5xbXBrsVbl9s7TSPLs8PoApHNNXHZzV/9i0cdFct3wQqvLnEJFKsEKBbarJReLdXlOw5YeLhX3N6XgJ6cwfyEmNDFltp3jkJxqtTjlKTqodTRCVIFven0a6SQvsbJ9qt5habYhwz4cIfgppIl/EJ9aGL4tniYmbQtrZkb/84HJhP1l/M4NJHe3FtOZvCmL4Rz/dB+TxccAnxul4yX9LUM180dxnY/hi3UVAVoAR45I9ytzt77Kg==,iv:GeH6P7gu7vwENO8w0my2L4TDewLm6E0zw7cnWceMeXQ=,tag:L0r82LIHVrMlBsnmdavSKA==,type:str]
sops:
    age:
        - recipient: age1tlmg2hsr6nag9cq6ws3h5r7fpzw6ekdh35av69uzetrth46f9vpsa8hqz9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T0JFMHNxc1IwTWxMVDB1
            VXJIU1RXeU9NTUN6SzhST0p4UnhHblRsSHdnCjJZRlN3bXhJaWVTT3VUcFpNS1Va
            NUIrVm5SUEhZeUovRzR4Rk93elhtNDAKLS0tIDlrbFdKd1V2NDJTMDRXSHVPM3A2
            bEIxYldOUjJrS1VValM0cHdKMm95NHMKUnYcneqF+WxelwLpqhw9t0sJK4oawKir
            Gaw6tiO0GN0Uy+4FSGBV21dAOW+iLKIyvLp/Oh5vZq03p4Y1cbe1Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-30T17:30:37Z"
    mac: ENC[AES256_GCM,data:HXZFkdPZyyqB3Vljgh57FD1CTnJzmeLqHAAHU0somzFw7H9ioRqANsXS+AUsEJBBNvyy/KX7OmafDUJFPJwo2zfUOreJENbi5HDfxP4NvuNzPU9KuWDN6fjRaIyg4O1IIxduPj9FkvpXPCMrePFLYckIFABYTYiP1o/C8WmMdHM=,iv:zr9KL7g9HaVzOHIthkVNUZW/GcDviAKod+8nrETH7UQ=,tag:i6Ldn6B5wYyKZu+EJFUqEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
