---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: &clusterName tivoli

endpoint: https://k8s.homelab.internal:6443

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.10.4
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.33.1

additionalApiServerCertSans: &sans
  - k8s.homelab.internal
  - &talosControlplaneVip 192.168.10.30
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: talos.homelab.internal
    ipAddress: 192.168.10.31
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    installDiskSelector:
      model: "KBG40ZNS512G*"
    networkInterfaces:
      - interface: eno1
        dhcp: true
        vip:
          ip: *talosControlplaneVip

controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *clusterName
    topology.kubernetes.io/zone: m

  extraManifests: &extraManifests
    - ./ups.yaml

  schematic: &schematic
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/i915
          - siderolabs/mei
          - siderolabs/thunderbolt

  patches:
    # Configure containerd
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
              [plugins."io.containerd.grpc.v1.cri".containerd]
                discard_unpacked_layers = false
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                discard_unpacked_layers = false

    # Disable search domain everywhere
    - |-
      machine:
        network:
          disableSearchDomain: true

    # Enable host dns
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false

    # Mount openebs-hostpath in kubelet
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/mnt/extra
              type: bind
              source: /var/mnt/extra
              options:
                - rbind
                - rshared
                - rw

    # Configure kubelet
    - |-
      machine:
        kubelet:
          extraConfig:
            maxPods: 150
          nodeIP:
            validSubnets:
                - 192.168.10.0/24

    # Enable MutatingAdmissionPolicy
    - |-
      cluster:
        apiServer:
          extraArgs:
            runtime-config: admissionregistration.k8s.io/v1alpha1=true
            feature-gates: MutatingAdmissionPolicy=true

    # Configure cluster
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        coreDNS:
            disabled: true
        proxy:
          disabled: true
        scheduler:
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway

    # Configure etcd
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 192.168.10.0/24

    # Configure NFS mount options
    - |
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              noatime=True
              nconnect=16

    # Configure static host entries
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: 192.168.10.30
              aliases:
                - k8s.homelab.internal

    # Configure custom sysctls
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_instances: 8192    # Watchdog
          fs.inotify.max_user_watches: 1048576   # Watchdog
          user.max_user_namespaces: 11255        # User namespaces
          net.core.rmem_max: 67108864            # Cloudflared / QUIC
          net.core.wmem_max: 67108864            # Cloudflared / QUIC

    # Configure udev rules
    - |-
      machine:
        udev:
          rules:
            # Intel GPU
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - actions-runner-system
              - system-upgrade
